#DinD with GitLab container registry
stages:
  - unit-Jenkinsfile
  - integration-Jenkinsfile
  - maven-build
  - image-build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  IMAGE_TAG: $CI_REGISTRY_IMAGE/employee-api:$CI_COMMIT_REF_SLUG

before_script:
  - export MAVEN_USER_HOME=$(pwd)/.m2

unit-test:
  stage: unit-Jenkinsfile
  image: maven:3.8.5-openjdk-17
  script:
    - mvn clean Jenkinsfile -B
  artifacts:
    paths:
      - "target/test-reports"
    when: always
    expire_in: 1 h

integration-test:
  stage: integration-Jenkinsfile
  image: maven:3.8.5-openjdk-17
  script:
    - mvn clean verify -DskipUnitTests -B
  artifacts:
    paths:
      - "target/test-reports"
    when: always
    expire_in: 1 h

maven-build:
  stage: maven-build
  image: maven:3.8.5-openjdk-17
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

image-build:
  stage: image-build
  image:
    docker:latest   #primary container
  services:
    - docker:dind   #secondary container
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG